web:
  restart: on-failure
  build: ./web
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - app:/usr/src/app
    - appstatic:/usr/src/app/static
  env_file: .env
  environment:
    DEBUG: 'true'
  command: uwsgi http :8000 --module docker_django.wsgi:application

nginx:
  restart: on-failure
  build: ./nginx
  ports:
    - "80:80"
  volumes:
    - nginx:/www/static
  volumes_from:
    - web
  links:
    - web:web

postgres:
  restart: on-failure
  image: postgres:latest
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

redis:
  restart: on-failure
  image: redis:latest
  ports:
    - "6379:6379"
  volumes:
    - redisdata:/data